apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leaderboard-api
spec:  
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: leaderboardwebapi
        image: clouddemo.azurecr.io/leaderboardwebapi:457 
        ports:
        - containerPort: 80       
      imagePullSecrets:
      - name: clouddemoimages

