apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leaderboard-api
spec:  
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: leaderboardwebapi
        image: clouddemo.azurecr.io/leaderboardwebapi:458          
      imagePullSecrets:
      - name: clouddemoimages


