apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leaderboard-api
  namespace: servicedemo
spec:  
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: leaderboardwebapi
        image: clouddemo.azurecr.io/leaderboardwebapi:457   
        env:        
        - name: Serilog__MinimumLevel__Default
          value: "Warning"
        - name: ConnectionStrings__LeaderboardContext
          valueFrom:
            secretKeyRef:
              name: sqlserver
              key: connectionstring
        ports:
        - containerPort: 80 
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 10 
          failureThreshold: 3    
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 10 
          failureThreshold: 3     
      imagePullSecrets:
      - name: clouddemoimages


