apiVersion: v1
kind: Secret
metadata:
  name: sqlserver
type: Opaque
data:
  connectionstring: U2VydmVyPXRjcDpnYW1pbmdkYnNlcnZlci5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0luaXRpYWwgQ2F0YWxvZz1nYW1pbmctZGF0YWJhc2U7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9Y2xvdWR1c2VyO1Bhc3N3b3JkPWFiYzEyMyFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz1GYWxzZTtFbmNyeXB0PVRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1GYWxzZTtDb25uZWN0aW9uIFRpbWVvdXQ9MzA7